site_name: ZVM
site_url: https://zvm.run
theme:
  name: terminal
plugins:
  - mkdocstrings
nav:
  - About: index.md
  - Standard Library:
    - std-methods.md
    - std-data.md
  - Developer Guide:
    - api.md
