site_name: Sequence
site_url: https://sequence.wiki
theme:
  name: terminal
  logo: docs/img/sequence.png
  custom_dir: docs/custom_theme/
plugins:
  - mkdocstrings
nav:
  - About: README.md
  - sequence.md
  - std.md
  - api.md
extra_css: [extra.css]
