site_name: Collagen
site_url: https://collagen.dev
theme:
  name: terminal
  custom_dir: docs/custom_theme/
plugins:
  - mkdocstrings
nav:
  - About: README.md
  - std.md
  - api.md
extra_css: [extra.css]
