site_name: ZVM
site_url: https://zvm.run
theme:
  name: terminal
  custom_dir: docs/custom_theme/
plugins:
  - mkdocstrings
nav:
  - index.md
  - Standard Library:
    - std-methods.md
    - std-data.md
  - api.md
extra_css: [extra.css]
