site_name: Sequence
site_url: https://sequence.dev
theme:
  name: terminal
  logo: docs/img/sequence.png
  custom_dir: docs/custom_theme/
plugins:
  - mkdocstrings
nav:
  - About: README.md
  - procedure.md
  - std.md
  - api.md
extra_css: [extra.css]
